[package]
name = "kvs"
version = "0.1.0"
authors = ["A certain talent <talent@gmail.com>"]
description = "A key-value store"
edition = "2021"

[dependencies]
clap = "2.32.0"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
